name: Feature Request
description: Suggest a new feature or enhancement for Archon V2 Beta
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - coleam00
  - Wirasm

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! This is an early beta project, so we're open to new ideas.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a pain point you're experiencing?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "The feature could work by..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of any alternative solutions or features?
      placeholder: "Another way to solve this could be..."
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Which component does this affect?
      multiple: true
      options:
        - Frontend (React UI)
        - Backend (FastAPI Server)
        - MCP Server
        - Agents (PydanticAI)
        - Database
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: "Here's a mockup of how it could look..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation
          required: false
